<#
.SYNOPSIS
    Creates a WPF MenuItem object.

.DESCRIPTION
    Creates a WPF MenuItem object.

    Supports nested scriptblocks as is standard but also a shorthand syntax
    where the name of each MenuItem is separated by a forward slash.

    Conventionally, menu items that have an underscore before a letter (_File)
    will use that letter as an accelerator key. That is supported for backwards
    compatibility but, for clarity, I have added and recommend using a new syntax
    in which the accelerator key is wrapped in parentheses, e.g. (F)ile.

    Since registered object names cannot contain spaces or most punctuation, the
    registered name is generated by stripping out all non-alphanumeric characters.
    The header keeps the original formatting with the accelerator key parentheses
    removed for ease of editing.

    MenuItem 'NameOne/NameTwo/NameThree' {...}

.EXAMPLE
    Create a menu item with an accelerator key using the new recommended syntax.

    MenuItem '(F)ile' { ... }

.EXAMPLE
    Create a nested menu structure with accelerator keys using the new recommended syntax.

    MenuItem '(F)ile/(N)ew/(P)roject' { ... }

.EXAMPLE
    Disable a block of code without commenting it out by using a negative prefix.

    -MenuItem 'MyItem' { ...code... }

.LINK
    https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.menuitem
#>
function MenuItem {
    [CmdletBinding(DefaultParameterSetName = 'ScriptBlock')]
    [Alias('-MenuItem')]
    [OutputType([void], [System.Windows.Controls.MenuItem])]
    param(
        [Parameter(ParameterSetName = 'Name', Position = 0)]
        [ValidateScript({ -not ($_ -is [scriptblock]) })]
        [ValidateNotNullOrEmpty()]
        [string] $Name = '__Nameless__',

        [Parameter(Mandatory, ParameterSetName = 'Name', Position = 1)]
        [Parameter(Mandatory, ParameterSetName = 'ScriptBlock', Position = 0)]
        [ScriptBlock] $ScriptBlock,

        [switch] $NoAutoAttach
    )

    if ($MyInvocation.InvocationName.StartsWith('-')) {
        Write-WPFDisabledBlockWarning -Invocation $MyInvocation -Name $Name
        return
    }

    try {
        # For strings like '_File/_Exit', split on the first occurence of '/'
        # RemainingNames will be used to create nested MenuItems
        $FirstName, $RemainingNames = $Name.Split('/', 2)

        # Support an alternative, in my opinion more intuitive,
        # accessor syntax: (F)ile
        $HeaderName = $FirstName.Replace('(', '_').Replace(')', '')

        # WPF names cannot contain spaces or most punctuation.
        # Keep readable headers while generating a safe backing name.
        $ObjectName = $HeaderName -replace '[^\w]', ''
        if (-not $ObjectName) {
            throw "MenuItem name '$Name' does not contain any valid name characters."
        }

        # Check if object already exists, if not, create one
        $WPFObject = Get-WPFRegisteredObject $ObjectName -ErrorAction SilentlyContinue
        if (-not $WPFObject) {
            $WPFObject = [System.Windows.Controls.MenuItem] @{
                Name = $ObjectName
                Header = $HeaderName
            }
            if ($ObjectName -ne '__Nameless__') { Register-WPFObject $ObjectName $WPFObject }
        }

        Add-WPFType $WPFObject 'Control'
    } catch {
        Write-Error "Failed to create '$Name' (MenuItem) with error: $_"
    }

    # Auto-attach to parent if one exists
    $Parent = $PSCmdlet.GetVariableValue('this')
    $WasAutoAttached = $False
    if (-not $NoAutoAttach -and $Parent -and -not $WPFObject.Parent) {
        if ($Parent -is [System.Windows.Window]) {
            Write-Debug "Beginning app-menu auto-attach for $Name (MenuItem)"
            $Menu = Get-WPFMenu -Window $Parent
            $AppRootProperty = $Parent.PSObject.Properties['_WPFAppRoot']
            if (-not $Menu -and $AppRootProperty.Value) {
                $Menu = New-WPFMenu -Window $Parent
            }
            if ($Menu) {
                Add-WPFObject $Menu $WPFObject
                $WasAutoAttached = $True
            }
        } else {
            Write-Debug "Beginning auto-attach for $Name (MenuItem)"
            Add-WPFObject $Parent $WPFObject
            $WasAutoAttached = $True
        }
    }

    # Recurse until we exhaust all names and get the resulsting child items
    # If we're processing RemainingNames, assume that the scriptblock was passed
    # to the deepest MenuItem
    if ($RemainingNames) {
        Write-Debug "Processing child elements for $Name (MenuItem)"
        $ChildObjects = MenuItem -Name $RemainingNames -ScriptBlock $ScriptBlock
        Update-WPFObject $WPFObject $ChildObjects
    }
    # Or else see if we got a script block. The last MenuItem should always have one.
    elseif ($ScriptBlock) {
        Write-Debug "Processing child elements for $Name (MenuItem)"
        Update-WPFObject $WPFObject $ScriptBlock
    }
    # Since Scriptblock is mandatory this scenario should never happen.
    else {
        Write-Error "Something unexpected occurred constructing '$Name' (MenuItem)"
    }

    if (-not $WasAutoAttached) {
        return $WPFObject
    }
}
